const users = [
    {
        username: "AK47",
        status: "Active",
        rank: 'Private',
        level: "2 (1.00%)",
        balance: "127,000",
    },
    {
        username: "ARH",
        status: "Active",
        rank: 'Corporal',
        level: "3 (1.50%)",
        balance: "135,992",
    },
    {
        username: "Aaraj",
        status: "Active",
        rank: 'Corporal',
        level: "3 (1.50%)",
        balance: "61,829",
    },
    {
        username: "Abed Saad",
        status: "Active",
        rank: "Noob",
        level: "0 (0.00%)",
        balance: "46,606",
    },
    {
        username: "Abou Jix" ,
        status: "Active" ,
        rank: "Noob" ,
        level: "0 (0.00%)",
        balance: "244,709",
    },
    {
        username: "Alec",
        status: "Active",
        rank: "Corporal",
        level:"3 (1.50%)" ,
        balance: "90,096",
    },
    {
        username: "AliGhandour964",
        status: "Active",
        rank: "Noob",
        level: "0 (0.00%)",
        balance: "79,976",
    },
    {
        username: "AndrawuS",
        status: "Active",
        rank:"Noob",
        level: "0 (0.00%)",
        balance: "47,983",
    },
    {
        username: "Andrew",
        status: "Active",
        rank: "Private",
        level: "2 (1.00%)",
        balance : "2,716",
    },
    {
        username: "Andrew Morkos",
        status: "Active",
        rank: "Noob",
        level: "0 (0.00%)",
        balance: "0",
    },
    {
        username: "Andrew123",
        status: "Active",
        rank: "Noob",
        level: "0 (0.00%)",
        balance: "60,749",
    },
    {
        username: "Anthony",
        status: "Active",
        rank : "Private",
        level : "2 (1.00%)",
        balance: "40,450",
    },
    {
        username: "Antonio",
        status: "Active",
        rank: "Noob",
        level : "0 (0.00%)",
        balance: "67,862",
    },
    {
        username: "Balachi",
        status: "Active",
        rank: "Private",
        level: "2 (1.00%)",
        balance: "80,750",
    },
    {
        username: "Campus",
        status: "Active",
        rank: "Noob",
        level: "0 (0.00%)",
        balance: "64,913",
    },
    {
        username: "CarlosS",
        status: "Active",
        rank: "Noob",
        level : "0 (0.00%)",
        balance : "112,966",
    },
    {
        username: "Charbel.Chammai",
        status: "Active",
        rank: "Noob",
        level: "0 (0.00%)",
        balance: "219,995",
    },
    {
        username: "CharbelR",
        status: "Active",
        rank: "Sergeant",
        level: "4 (2.00%)",
        balance: "112,268",
    },
    {
        username: "DHayek",
        status: "Active",
        rank: "Noob",
        level : "0 (0.00%)",
        balance: "19,794",
    },
    {
        username: "Daniel Hayek",
        status: "Active",
        rank: "Noob",
        level: "0 (0.00%)",
        balance: "39,688",
    },
    {
        username: "Drake",
        status: "Active",
        rank: "Private",
        level : "2 (1.00%)",
        balance: "173,400",
    },
    {
        username: "ELIAS",
        status: "Active",
        rank: "Private",
        level: "2 (1.00%)",
        balance: "143,850",
    },
    {
        username: "El Khatir",
        status: "Active",
        rank: "Noob",
        level: "0 (0.00%)",
        balance: "104,701",
    },
    {
        username: "Elhayek",
        status: "Active",
        rank: "Noob",
        level: "0 (0.00%)",
        balance: "31,303",
    },
    {
        username: "EliasBassil",
        status: "Active",
        rank:"Noob",
        level : "0 (0.00%)",
        balance: "16,540",
    },
    {
        username: "ElieJoeHayek",
        status: "Active",
        rank: "Noob",
        level: "0 (0.00%)",
        balance: "0",
    },
    {
        username: "Elie_Hayek",
        status: "Active",
        rank: "Noob",
        level: "0 (0.00%)",
        balance: "26,402",
    },
    {
        username: "Elio Aaraj",
        status: "Active",
        rank: "Noob",
        level: "0 (0.00%)",
        balance: "83,290",
    },
    {
        username: "Emil chammai",
        status: "Active",
        rank:"Corporal",
        level: "3 (1.50%)",
        balance: "36,062",
    },
    {
        username: "Emil.Hajj",
        status: "Active",
        rank: "Noob",
        level: "0 (0.00%)",
        balance: "33,507",
    },
    {
        username: "FadiElHayek2",
        status: "Active",
        rank: "Noob",
        level: "0 (0.00%)",
        balance: "221,611",
    },
    {
        username: "Georges",
        status:"Active",
        rank: "Noob",
        level: "0 (0.00%)",
        balance: "51,637",
    },
    {
        username: "H.Rawas",
        status : "Active",
        rank: "Noob",
        level: "0 (0.00%)",
        balance: "123,318",
    },
    {
        username: "Hassan Keserwani",
        status: "Active",
        rank: "Noob",
        level: "0 (0.00%)",
        balance: "0",
    },
    {
        username: "Herloww",
        status: "Active",
        rank : "Noob",
        level: "0 (0.00%)",
        balance: "0",
    },
    {
        username: "Hussein Mohaidly",
        status: "Active",
        rank: "Noob",
        level: "0 (0.00%)",
        balance: "128,319",
    },
    {
        username: "Ibrahim Berro",
        status: "Active",
        rank : "Noob",
        level: "0 (0.00%)",
        balance: "20,311",
    },
    {
        username: "Issa",
        status: "Active",
        rank: "Noob",
        level: "0 (0.00%)",
        balance: "13,004",
    },
    {
        username: "Jeanh",
        status: "Active",
        rank: "Corporal",
        level: "3 (1.50%)",
        balance: "202,427",
    },
    {
        username: "Joe",
        status: "Active",
        rank: "Private",
        level: "2 (1.00%)",
        balance: "9,800",
    },
    {
        username: "Johnny_76",
        status: "Active",
        rank : "Noob",
        level: "0 (0.00%)",
        balance : "146,596",
    },
    {
        username: "Joseph",
        status: "Active",
        rank:"Noob",
        level: "0 (0.00%)",
        balance: "124,985",
    },
    {
        username: "Khalil bakradoni",
        status: "Active",
        rank: "Corporal",
        level: "3 (1.50%)",
        balance: "359,154",
    },
    {
        username:"Kozmo",
        status: "Active",
        rank:"Sergeant",
        level: "4 (2.00%)",
        balance: "23,264",
    },
    {
        username: "LBOUNA",
        status: "Active",
        rank: "Corporal",
        level : "3 (1.50%)",
        balance: "54,075",
    },
    {
        username: "Lahoud",
        status: "Active",
        rank: "Noob",
        level: "0 (0.00%)",
        balance: "112,886",
    },
    {
        username: "MAJD9",
        status: "Active",
        rank: "Noob",
        level: "0 (0.00%)",
        balance: "0",
    },
    {
        username: "MAjd0286",
        status: "Active",
        rank: "Noob",
        level: "0 (0.00%)",
        balance: "0",
    },
    {
        username: "MahdiR",
        status: "Acitve",
        rank: "Noob",
        level: "0 (0.00%)",
        balance: "0",
    },
    {
        username: "Majd",
        status: "Active",
        rank: "Noob",
        level: "0 (0.00%)",
        balance: "9,962",
    },
    {
        username: "Mani",
        status: "Active",
        rank: "Noob",
        level: "0 (0.00%)",
        balance: "73,296",
    },
    {
        username: "MhmdM",
        status: "Active",
        rank: "Noob",
        level: "0 (0.00%)",
        balance : "126,147",
    },
    {
        username: "Mike12",
        status: "Active",
        rank: "Noob",
        level: "0 (0.00%)",
        balance: "134,987",
    },
    {
        username: "Nachefanto",
        status: "Active",
        rank: "Noob",
        level: "0 (0.00%)",
        balance: "53,324",
    },
    {
        username: "Nicolas.Chammai",
        status: "Active",
        rank : "Noob",
        level: "0 (0.00%)",
        balance: "134,881",
    },
    {
        username: "Payar_hbk",
        status: "Active",
        rank: "Noob",
        level: "0 (0.00%)",
        balance: "0",
    },
    {
        username: "Ralph",
        status: "Active",
        rank: "Noob",
        level: "0 (0.00%)",
        balance: "73,308",
    },
    {
        username: "RayanM",
        status: "Active",
        rank: "Noob",
        level: "0 (0.00%)",
        balance: "169,699",
    },
    {
        username:"Rayen Makhoul",
        status: "Active",
        rank: "Noob",
        level: "0 (0.00%)",
        balance: "58,235",
    },
    {
        username: "Ribal12",
        status: "Active",
        rank: "Noob",
        level: "0 (0.00%)",
        balance:"13.228",
    },
    {
        username: "Roy",
        status: "Acitve",
        rank : "Private",
        level: "2 (1.00%)",
        balance: "56,821",
    },
    {
        username: "Ryan",
        status: "Active",
        rank: "Private",
        level: "2 (1.00%)",
        balance: "64,320",
    },
    {
        username: "Saliba",
        status: "Active",
        rank:"Sergeant",
        level: "4 (2.00%)",
        balance: "9,706",
    },
    {
        username: "Sary",
        status: "Active",
        rank: "Noob",
        level: "0 (0.00%)",
        balance: "134,491",
    },
    {
        username: "Tangar",
        status: "Active",
        rank: "Private",
        level: "2 (1.00%)",
        balance: "6,450",
    },
    {
        username: "Terrminator",
        status: "Active",
        rank: "Noob",
        level: "0 (0.00%)",
        balance: "11,649",
    },
    {
        username: "Tony33",
        status: "Active",
        rank: "Noob",
        level: "0 (0.00%)",
        balance: "79,996",
    },
    {
        username: "Yorgo",
        status: "Active",
        rank: "Noob",
        level: "0 (0.00%)",
        balance: "21,656",
    },
    {
        username: "YorgoKhoury",
        status: "Active",
        rank: "Noob",
        level: "0 (0.00%)",
        balance: "54,961",
    },
    {
        username: "Yvan",
        status : "active",
        rank :  "Noob",
        level: "0 (0.00%)",
        balance: "119,833",
    },
    {
        username: "Zidane Moussa",
        status: "Active",
        rank: "Noob",
        level: "0 (0.00%)",
        balance: "48,313",
    },
    {
        username: "abouelfir",
        status: "Active",
        rank: "Noob",
        level: "0 (0.00%)",
        balance: "36,634",
    },
    {
        username: "ahmad11",
        status: "Active",
        rank: "Noob",
        level: "0 (0.00%)",
        balance: "18,257",
    },
    {
        username: "alidaoud",
        status: "Active",
        rank : "Noob",
        level: "0 (0.00%)",
        balance: "124,985",
    },
    {
        username: "bachar",
        status: "Active",
        rank : "Noob",
        level: "0 (0.00%)",
        balance: "136,554",
    },
    {
        username: "boukarim",
        status: "Active",
        rank: "Private",
        level : "2 (1.00%)",
        balance: "70,810",
    },
    {
        username: "bounjuss",
        status: "Active",
        rank: "Private",
        level: "2 (1.00%)",
        balance: "191,900",
    },
    {
        username: "bryanHayek",
        status: "Active",
        rank : "Noob",
        level:"0 (0.00%)",
        balance: "0",
    },
    {
        username: "chaalan",
        status: "Active",
        rank :"Noob",
        level: "0 (0.00%)",
        balance: "108,215",
    },
    {
        username: "charbel",
        status : "Active",
        rank: "Noob",
        level: "0 (0.00%)",
        balance: "83,320",
    },
    {
        username: "charbel el hajj",
        status: "Active",
        rank: "Noob",
        level: "0 (0.00%)",
        balance: "106,648",
    },
    {
        username: "cheme3e",
        status: "Active",
        rank: "Sergeant",
        level: "4 (2.00%)",
        balance: "24,040",
    },
    {
        username: "choche",
        status: "Active",
        rank: "Noob",
        level: "0 (0.00%)",
        balance: "14,963",
    },
    {
        username: "coco11",
        status: "Active",
        rank: "Corporal",
        level: "3 (1.50%)",
        balance: "8,356",
    },
    {
        username:'dahouk',
        status: 'Active',
        rank: 'Noob',
        level: '0 (0.00%)',
        balance: '128,319',
    },
    {
        username:'davidloute',
        status: 'Active',
        rank: "Noob",
        level: "0 (0.00%)",
        balance: '1,638',
    },
    {
        username: 'eddysh',
        status: 'Active',
        rank : 'Private',
        level : "2 (1.00%)",
        balance: '795,252',
    },
    {
        username: "ejm548",
        status: 'Active',
        rank:'Noob',
        level: '0 (0.00%)',
        balance: "63,226",
    },
    {
        username:'elena',
        status: 'Active',
        rank:'Noob',
        level: '0 (0.00%)',
        balance: '19,944',
    },
    {
        username: 'eliassaab',
        status: "Active",
        rank : 'Noob',
        level: '0 (0.00%)',
        balance: '3,314',
    },
    {
        username: 'fabienesber10',
        status: 'Active',
        rank: 'Noob',
        level: '0 (0.00%)',
        balance: '3,222',
    },
    {
        username: 'halim',
        status: 'Active',
        rank: 'Corporal',
        level: "3 (1.50%)",
        balance: '5,370',
    },
    {
        username: 'houssam,m',
        status: 'Active',
        rank: "Noob",
        level: "0 (0.00%)",
        balance: "0",
    },
    {
        username: 'huss',
        status: "Active",
        rank: "Noob",
        level: "0 (0.00%)",
        balance: "61,559",
    },
    {
        username:"jad1999",
        status: "Active",
        rank :"Sergeant",
        level: "4 (2.00%)",
        balance: "24,814",
    },
    {
        username: "khalil001",
        status: "Active",
        rank : "Corporal",
        level : "3 (1.50%)",
        balance: "5,500",
    },
    {
        username: "khokho",
        status: "Active",
        rank: "Private",
        level: "2 (1.00%)",
        balance: "152,859",
    },
    {
        username: "lallas",
        status: "Active",
        rank: 'Private',
        level: '2 (1.00%)',
        balance: '156,650',
    },
    {
        username: 'mahdi',
        status: "Active",
        rank: 'Noob',
        level: '0 (0.00%)',
        balance: '158,325',
    },
    {
        username: 'marc hayek',
        status: "Active",
        rank: "Private",
        level: '2 (1.00%)',
        balance: "86,020",
    },
    {
        username: "marcoukaw",
        status : 'Active',
        rank: "Private",
        level: "2 (1.00%)",
        balance: "31,346",
    },
    {
        username: 'mehdi',
        status: 'Active',
        rank: 'Noob',
        level: "0 (0.00%)",
        balance: '24,865',
    },
    {
        username: 'mhaydli11',
        status: 'Active',
        rank: 'Noob',
        level: '0 (0.00%)',
        balance: '0',
    },
    {
        username: 'mohammad',
        status: 'Active',
        rank: 'Noob',
        level: '0 (0.00%)',
        balance: '98,313',
    },
    {
        username: 'mohammad23',
        status: 'Active',
        rank : 'Noob',
        level: "0 (0.00%)",
        balance: '86,644',
    },
    {
        username: 'mohcine',
        status: 'Active',
        rank: 'Noob',
        level: '0 (0.00%)',
        balance: '104,901',
    },
    {
        username:'nicolas',
        status: 'Active',
        rank : 'Noob',
        level: '0 (0.00%)',
        balance: '64,993',
    },
    {
        username: 'nicolas faf',
        status: 'Active',
        rank :'Noob',
        level: '0 (0.00%)',
        balance: '58,325',
    },
    {
        username:'olive',
        status: 'Active',
        rank : 'Noob',
        level: "0 (0.00%)",
        balance: '1,647',
    },
    {
        username: 'professor beard',
        status: "Active",
        rank : 'Noob',
        level: "0 (0.00%)",
        balance: '9,922',
    },
    {
        username: 'rafi',
        status: 'Active',
        rank : 'Noob',
        level: "0 (0.00%)",
        balance: '144,949',
    },
    {
        username: 'rida',
        status: 'Active',
        rank: 'Noob',
        level: '0 (0.00%)',
        balance: '118,077',
    },
    {
        username: 'semaan',
        status: 'Active',
        rank: 'Private',
        level: '2 (1.00%)',
        balance: '3,850',
    },
    {
        username: 'sikosem',
        status: 'Active',
        rank: 'Sergeant',
        level: '4 (2.00%)',
        balance: '26',
    },
    {
        username: 'thea',
        status: 'Active',
        rank: 'Corporal',
        level: '3 (1.50%)',
        balance: '11,944',
    },
    {
        username:'tino nakhle',
        status: 'Active',
        rank : 'Noob',
        level: '0 (0.00%)',
        balance: "41,635",
    },
    {
        username: 'wafoukaw',
        status: 'Active',
        rank: 'Noob',
        level : "0 (0.00%)",
        balance: '81,363',
    },
    {
        username:'wassim younan',
        status: 'Active',
        rank: 'Noob',
        level: '0 (0.00%)',
        balance: '111,449',
    },
    {
        username: 'xilix',
        status: 'Active',
        rank: 'Corporal',
        level: '3 (1.50%)',
        balance: '52,826',
    },
];

export default users;